version: 0.2
env:
  parameter-store:
    LW_ACCOUNT: "LW_ACCOUNT"
    LW_API_KEY: "LW_API_KEY"
    LW_API_SECRET: "LW_API_SECRET"
phases:
  build:
    commands:
      - export LW_ACCOUNT=$LW_ACCOUNT
      - export LW_API_KEY=$LW_API_KEY
      - export LW_API_SECRET=$LW_API_SECRET
      - curl https://raw.githubusercontent.com/lacework/go-sdk/master/cli/install.sh | bash
      - lacework compliance aws run-assessment $STAGING_ACCOUNT_ID
      - lacework compliance aws get-report $STAGING_ACCOUNT_ID --json | jq '.summary[0].num_severity_1_non_compliance'


